"""Initial migration.

Revision ID: 41a9092a460c
Revises: 
Create Date: 2024-09-16 02:37:32.799858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a9092a460c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=10), nullable=True),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
