"""Initial migration.

Revision ID: 9684a590d16a
Revises: 905a3bd521e2
Create Date: 2024-09-16 05:18:38.012981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9684a590d16a'
down_revision = '905a3bd521e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('token', sa.String(length=12), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
