"""Initial migration.

Revision ID: ea58c4a390a5
Revises: 9481d1bfd941
Create Date: 2024-09-16 02:42:21.566759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea58c4a390a5'
down_revision = '9481d1bfd941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('mobile', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('token', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
